# Generated by Django 3.0.6 on 2020-05-09 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibloteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('numPages', models.IntegerField()),
                ('statu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibloteca.Statu')),
            ],
        ),
    ]
