# Generated by Django 3.0.6 on 2020-05-09 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloteca', '0004_progressbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 1, 49, 55, 56635)),
        ),
    ]
