# Generated by Django 3.0.6 on 2020-05-11 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloteca', '0005_auto_20200509_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currentPage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progressbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 0, 52, 53, 340363)),
        ),
    ]
