# Generated by Django 3.0.6 on 2020-05-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloteca', '0006_auto_20200511_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='ProgressBook',
        ),
    ]
