# Generated by Django 3.0.6 on 2020-05-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibloteca', '0008_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='currentPage',
        ),
    ]
