# Generated by Django 3.0.6 on 2020-05-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloteca', '0009_remove_book_currentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='currentPage',
            field=models.IntegerField(),
        ),
    ]
