# Generated by Django 3.0.6 on 2020-05-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloteca', '0010_auto_20200514_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='currentPage',
            field=models.IntegerField(default=0),
        ),
    ]
