# Generated by Django 3.0.6 on 2020-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibloteca', '0013_auto_20200516_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='satatu',
            field=models.IntegerField(default=0),
        ),
    ]
