# Generated by Django 3.0.6 on 2020-05-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibloteca', '0014_state_satatu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='statu',
        ),
        migrations.RemoveField(
            model_name='state',
            name='satatu',
        ),
        migrations.AddField(
            model_name='state',
            name='statu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibloteca.Statu'),
        ),
    ]
